// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUw-zgo5Jnise270YdiP2we114Gi_B-B4',
    appId: '1:262229963964:web:38a4474bbb07faaa720cb9',
    messagingSenderId: '262229963964',
    projectId: 'wear60-1e512',
    authDomain: 'wear60-1e512.firebaseapp.com',
    storageBucket: 'wear60-1e512.firebasestorage.app',
    measurementId: 'G-4YFPNBVNP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlGQafM0cL68wxtWrDYfT_OrJ4nQ3hP4',
    appId: '1:262229963964:android:d47fbecf72fa0bb2720cb9',
    messagingSenderId: '262229963964',
    projectId: 'wear60-1e512',
    storageBucket: 'wear60-1e512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ3dbtl-WEnzNnn3xEQlje-XPPO79FRwU',
    appId: '1:262229963964:ios:b347b1cd48453f16720cb9',
    messagingSenderId: '262229963964',
    projectId: 'wear60-1e512',
    storageBucket: 'wear60-1e512.firebasestorage.app',
    iosClientId: '262229963964-lvq5vjgoe2b7i9jktuqnbmlc03mpjgh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ3dbtl-WEnzNnn3xEQlje-XPPO79FRwU',
    appId: '1:262229963964:ios:b347b1cd48453f16720cb9',
    messagingSenderId: '262229963964',
    projectId: 'wear60-1e512',
    storageBucket: 'wear60-1e512.firebasestorage.app',
    iosClientId: '262229963964-lvq5vjgoe2b7i9jktuqnbmlc03mpjgh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleAuthDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUw-zgo5Jnise270YdiP2we114Gi_B-B4',
    appId: '1:262229963964:web:40f1133f3a77136c720cb9',
    messagingSenderId: '262229963964',
    projectId: 'wear60-1e512',
    authDomain: 'wear60-1e512.firebaseapp.com',
    storageBucket: 'wear60-1e512.firebasestorage.app',
    measurementId: 'G-BXBE7WN6C2',
  );

}